// ---- NPC registry ----------------------------------------------------------
// Maps mapId → npcId → visual + default dialog data.
export type NpcTheme = 'purple' | 'black' | 'blue' | 'red' | 'yellow';

export interface NpcPatrol {
  /** Direction of patrol movement */
  axis: 'x' | 'y';
  /** Total distance the NPC walks in each direction from spawn */
  distance: number;
  /** Movement speed in px/s */
  speed: number;
  /** Pause at each end in ms (default 0) */
  pauseMs?: number;
}

export interface NpcData {
  name: string;
  /** Default text when no quest overrides the dialog.
   *  Use string[] for multi-page dialogs (one entry per page). */
  text: string | string[];
  spriteKey: string;
  frame: number;
  scale: number;
  bodySize: { width: number; height: number };
  bodyOffset: { x: number; y: number };
  portrait?: string;
  animated?: boolean;
  repeatDelay?: number;
  delay?: number;
  flipX?: boolean;
  theme?: NpcTheme;
  patrol?: NpcPatrol;
  /** If set, the NPC stops animating once this collectible has been collected */
  stopAnimWhenCollected?: string;
}

export const NPC_REGISTRY: Record<string, Record<string, NpcData>> = {
  '16-json': {
    'purple-warrior': {
      name: 'Sir James - The Protector',
      text: 'Hey there, traveler.',
      spriteKey: 'purple-warrior-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purpleWarriorAvatar.png',
      theme: 'purple',
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
    'purple-pawn-idle': {
      name: 'Jake - The Pawn',
      text: 'I love my life!',
      spriteKey: 'purple-pawn-idle',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      theme: 'purple',
      flipX: true,
      animated: true,
    },
    'purple-monk': {
      name: 'One Without a Name',
      text: '...',
      spriteKey: 'purple-monk-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purpleMonkAvatar.png',
      theme: 'purple',
      animated: true,
      repeatDelay: 1000,
      delay: 1000,
    },
    'purple-pawn-idle-wood': {
      name: 'John - The Builder',
      text: 'Life of a pawn is hard',
      spriteKey: 'purple-pawn-idle-wood',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      flipX: true,
      theme: 'purple',
      animated: true,
      repeatDelay: 500,
      delay: 200,
    },
  },

  '16b-json': {
    'purple-warrior-black': {
      name: 'Sir James - The Protector of His Bussiness',
      text: 'Hey there, traveler.',
      spriteKey: 'black-warrior-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blackWarriorAvatar.png',
      theme: 'black',
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
    'black-warrior-16b': {
      name: 'The Mysterious Stranger',
      text: [`Soon, we'll conquer all.`, `You helped, so I'll let you live.`, `Go, don't test my patience.`],
      spriteKey: 'black-warrior-idle',
      frame: 4,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blackWarriorAvatar.png',
      theme: 'black',
      flipX: true,
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
    'black-lancer-guard-top-16b': {
      name: 'Mysterious Stranger',
      text: '...',
      spriteKey: 'black-lancer-defense',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 60, height: 35 },
      bodyOffset: { x: 120, y: 160 },
      portrait: 'gameAssets/blackLancerAvatar.png',
      theme: 'black',
      flipX: true,
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
    'black-lancer-guard-bot-16b': {
      name: 'Mysterious Stranger',
      text: '...',
      spriteKey: 'black-lancer-defense',
      frame: 4,
      scale: 0.75,
      bodySize: { width: 60, height: 35 },
      bodyOffset: { x: 120, y: 160 },
      portrait: 'gameAssets/blackLancerAvatar.png',
      theme: 'black',
      flipX: true,
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
  },

  '17-json': {
    'purple-pawn-idle': {
      name: 'Justin - Just Justin',
      text: ['Watch out for any green winds around here!', "I have seen a pirate touch it and POOF! He was gone."],
      spriteKey: 'purple-pawn-idle',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      theme: 'purple',
      animated: true,
      repeatDelay: 500,
    }
  },

  '27-json': {
    'blueMonkHeal': {
      name: 'Blue Monk',
      text: 'May the waters heal your spirit.',
      spriteKey: 'blueMonkHeal',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blueMonkAvatar.png',
      theme: 'blue',
      animated: true,
      repeatDelay: 500,
      delay: 500,
      stopAnimWhenCollected: 'artifact1',
    },
    'blueMonkHeal2': {
      name: 'Blue Monk',
      text: 'May the waters heal your spirit.',
      spriteKey: 'blueMonkHeal',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blueMonkAvatar.png',
      theme: 'blue',
      animated: true,
      repeatDelay: 700,
      delay: 400,
      stopAnimWhenCollected: 'artifact1',
    },
    'blueMonkHealReverse': {
      name: 'Blue Monk',
      text: 'The tides bring peace.',
      spriteKey: 'blueMonkHeal',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blueMonkAvatar.png',
      theme: 'blue',
      flipX: true,
      animated: true,
      repeatDelay: 1000,
      delay: 1000,
      stopAnimWhenCollected: 'artifact1',
    },
    'blueMonkHealReverse2': {
      name: 'Blue Monk',
      text: 'The tides bring peace.',
      spriteKey: 'blueMonkHeal',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blueMonkAvatar.png',
      theme: 'blue',
      flipX: true,
      animated: true,
      repeatDelay: 400,
      delay: 1000,
      stopAnimWhenCollected: 'artifact1',
    },
    'bluePawnAxeIdle': {
      name: 'Blue Pawn',
      text: 'Those guys are nuts!',
      spriteKey: 'bluePawnAxeIdle',
      frame: 0,
      scale: 0.8,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/bluePawnAvatar.png',
      theme: 'blue',
      animated: true,
      flipX: true,
    },
  },

  '18-json': {
    'purple-pawn-idle-hammer-18': {
      name: 'Jayce - The Builder',
      text: 'Life of a pawn is hard',
      spriteKey: 'purple-pawn-idle-hammer',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      flipX: true,
      theme: 'purple',
      animated: true,
      repeatDelay: 100,
      delay: 200,
    },
    'duck': {
      name: 'Duck',
      text: 'Quack',
      spriteKey: 'duck',
      frame: 0,
      scale: 1,
      bodySize: { width: 32, height: 32 },
      bodyOffset: { x: 0, y: 0 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      flipX: true,
      theme: 'red',
      animated: true,
      repeatDelay: 100,
      delay: 100,
      patrol: {
        axis: 'x',
        distance: 90,
        speed: 80,
        pauseMs: 1000,
      }
    }
  },

  '26-json': {
    'purple-pawn-idle-26': {
      name: 'Jack - The Sheppard',
      text: 'I used to be a warrior, but this life suits me better!',
      spriteKey: 'purple-pawn-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      theme: 'purple',
      animated: true,
    },
    'sheep-26-1': {
      name: 'Sheep',
      text: 'Baa!',
      spriteKey: 'sheep',
      frame: 1,
      scale: 0.85,
      bodySize: { width: 35, height: 30 },
      bodyOffset: { x: 50, y: 50 },
      theme: 'purple',
      animated: true,
    },
    'sheep-26-2': {
      name: 'Sheep',
      text: 'Baa! Baaaa! Baa!',
      spriteKey: 'sheep',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 25 },
      bodyOffset: { x: 50, y: 50 },
      theme: 'purple',
      animated: true,
    },
    'sheep-26-3': {
      name: 'Sheep',
      text: 'Baa!',
      spriteKey: 'sheep',
      frame: 3,
      scale: 0.75,
      bodySize: { width: 35, height: 25 },
      bodyOffset: { x: 50, y: 50 },
      theme: 'purple',
      animated: true,
    },
    'purple-pawn-idle-flip': {
      name: 'Jeff - The kid no one listens to',
      text: `I swear I've seen something in the bushes down there!`,
      spriteKey: 'purple-pawn-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/purplePawnAvatar.png',
      theme: 'purple',
      animated: true,
      flipX: true,
    },
    'black-warrior': {
      name: 'The Mysterious Stranger',
      text: '...',
      spriteKey: 'black-warrior-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/blackWarriorAvatar.png',
      theme: 'black',
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
    'black-lancer-idle': {
      name: 'Mysterious Stranger',
      text: '...',
      spriteKey: 'black-lancer-idle',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 45, height: 35 },
      bodyOffset: { x: 120, y: 160 },
      portrait: 'gameAssets/blackWarriorAvatar.png',
      theme: 'black',
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
    'black-lancer-idle2': {
      name: 'Mysterious Stranger',
      text: '...',
      spriteKey: 'black-lancer-idle',
      frame: 8,
      scale: 0.75,
      bodySize: { width: 45, height: 35 },
      bodyOffset: { x: 120, y:  160 },
      portrait: 'gameAssets/blackWarriorAvatar.png',
      theme: 'black',
      animated: true,
      repeatDelay: 200,
      delay: 200,
    },
  },

  '38-json': {
    'bluePawnIdleKnifeReverse': {
      name: 'Blue Pawn',
      text: [`I look dangerous, but don't worry. The dev decided I'll just stand here menacingly.`],
      spriteKey: 'bluePawnIdleKnife',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/bluePawnAvatar.png',
      theme: 'blue',
      flipX: true,
      animated: true,
    },
  },

  '28-json': {
    'temp': {
      name: 'Blue Warrior',
      text: [
        "The ancient forces are stirring in this region.",
        "I've been stationed here to keep watch. If you find anything unusual, bring it to me.",
      ],
      spriteKey: 'bluePawnIdleKnife',
      frame: 0,
      scale: 0.75,
      bodySize: { width: 35, height: 35 },
      bodyOffset: { x: 80, y: 85 },
      portrait: 'gameAssets/bluePawnAvatar.png',
      theme: 'blue',
      animated: true,
    },
  },

  '29-json': {
    'duck': {
      name: 'Magic Duck',
      text: [
        "Quack",
      ],
      spriteKey: 'duck',
      frame: 0,
      scale: 1,
      flipX: true,
      bodySize: { width: 32, height: 32 },
      bodyOffset: { x: 0, y: 0 },
      portrait: 'gameAssets/duck.png',
      theme: 'red',
      animated: false,
      repeatDelay: 200,
      delay: 200,
      
    },
    'sheep2': {
      name: 'Sheep',
      text: 'Baa!',
      spriteKey: 'sheepMove',
      frame: 1,
      scale: 0.85,
      bodySize: { width: 35, height: 30 },
      bodyOffset: { x: 50, y: 50 },
      theme: 'red',
      animated: true,
      repeatDelay: 100,
      delay: 100,
      patrol: {
        axis: 'x',
        distance: 20,
        speed: 90,
        pauseMs: 100,
      }
    },
    'sheep1': {
      name: 'Sheep',
      text: `This sheep doesn't talk`,
      spriteKey: 'sheepMove',
      portrait: 'gameAssets/duck.png',
      frame: 1,
      scale: 0.85,
      bodySize: { width: 35, height: 30 },
      bodyOffset: { x: 50, y: 50 },
      theme: 'red',
      animated: true,
      repeatDelay: 100,
      delay: 100,
      patrol: {
        axis: 'x',
        distance: 40,
        speed: 80,
        pauseMs: 1000,
      }
    },
  },
};
