// ---- NPC registry ----------------------------------------------------------
// Maps npcId (set as a custom property on Tiled objects) → visual + default
// dialog data.
export type NpcTheme = 'purple' | 'black' | 'blue' | 'red' | 'yellow';

export const NPC_REGISTRY: Record<
  string,
  {
    name: string;
    /** Default text when no quest overrides the dialog */
    text: string;
    spriteKey: string;
    frame: number;
    scale: number;
    bodySize: { width: number; height: number };
    bodyOffset: { x: number; y: number };
    portrait?: string;
    animated?: boolean;
    repeatDelay?: number;
    delay?: number;
    flipX?: boolean;
    theme?: NpcTheme;
  }
> = {
  'purple-warrior': {
    name: 'Purple Warrior',
    text: 'Hey there, traveler.',
    spriteKey: 'purple-warrior-idle',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/purpleWarriorAvatar.png',
    theme: 'purple',
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'purple-pawn-idle': {
    name: 'Purple Pawn',
    text: 'I love my life!',
    spriteKey: 'purple-pawn-idle',
    frame: 0,
    scale: 0.8,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/purplePawnAvatar.png',
    theme: 'purple',
    flipX: true,
    animated: true,
  },
  'purple-pawn-idle-26': {
    name: 'Purple Pawn Sheppard',
    text: 'I used to be a warrior, but this life suits me better!',
    spriteKey: 'purple-pawn-idle',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/purplePawnAvatar.png',
    theme: 'purple',
    animated: true,
    repeatDelay: 3000,
    delay: 3000,
  },
  'sheep-26-1': {
    name: 'Sheep',
    text: 'Baa!',
    spriteKey: 'sheep',
    frame: 1,
    scale: 0.85,
    bodySize: { width: 35, height: 30 },
    bodyOffset: { x: 50, y: 50 },
    theme: 'purple',
    animated: true,
  },
  'sheep-26-2': {
    name: 'Sheep',
    text: 'Baa!',
    spriteKey: 'sheep',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 25 },
    bodyOffset: { x: 50, y: 50 },
    theme: 'purple',
    animated: true,
  },
  'sheep-26-3': {
    name: 'Sheep',
    text: 'Baa!',
    spriteKey: 'sheep',
    frame: 3,
    scale: 0.75,
    bodySize: { width: 35, height: 25 },
    bodyOffset: { x: 50, y: 50 },
    theme: 'purple',
    animated: true,
  },
  'black-warrior': {
    name: 'Mysterious Stranger',
    text: '...',
    spriteKey: 'black-warrior-idle',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/blackWarriorAvatar.png',
    theme: 'black',
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'purple-monk': {
    name: 'One Without a Name',
    text: '...',
    spriteKey: 'purple-monk-idle',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/purpleMonkAvatar.png',
    theme: 'purple',
    animated: true,
    repeatDelay: 1000,
    delay: 1000,
  },
  'purple-pawn-idle-wood': {
    name: 'Purple Pawn',
    text: 'Life of a pawn is hard',
    spriteKey: 'purple-pawn-idle-wood',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/purplePawnAvatar.png',
    flipX: true,
    theme: 'purple',
    animated: true,
    repeatDelay: 500,
    delay: 200,
  },
  'purple-pawn-idle-hammer-18': {
    name: 'Purple Pawn',
    text: 'Life of a pawn is hard',
    spriteKey: 'purple-pawn-idle-hammer',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/purplePawnAvatar.png',
    flipX: true,
    theme: 'purple',
    animated: true,
    repeatDelay: 100,
    delay: 200,
  },
  'black-lancer-idle': {
    name: 'Mysterious Stranger',
    text: '...',
    spriteKey: 'black-lancer-idle',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 45, height: 35 },
    bodyOffset: { x: 120, y: 160 },
    portrait: 'gameAssets/blackWarriorAvatar.png',
    theme: 'black',
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'black-lancer-idle2': {
    name: 'Mysterious Stranger',
    text: '...',
    spriteKey: 'black-lancer-idle',
    frame: 8,
    scale: 0.75,
    bodySize: { width: 45, height: 35 },
    bodyOffset: { x: 120, y:  160 },
    portrait: 'gameAssets/blackWarriorAvatar.png',
    theme: 'black',
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'purple-warrior-black': {
    name: 'Purple? Warrior',
    text: 'Hey there, traveler.',
    spriteKey: 'black-warrior-idle',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/blackWarriorAvatar.png',
    theme: 'black',
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'black-warrior-16b': {
    name: 'Mysterious Stranger',
    text: '...',
    spriteKey: 'black-warrior-idle',
    frame: 4,
    scale: 0.75,
    bodySize: { width: 35, height: 35 },
    bodyOffset: { x: 80, y: 85 },
    portrait: 'gameAssets/blackWarriorAvatar.png',
    theme: 'black',
    flipX: true,
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'black-lancer-guard-top-16b': {
    name: 'Mysterious Stranger',
    text: '...',
    spriteKey: 'black-lancer-defense',
    frame: 0,
    scale: 0.75,
    bodySize: { width: 60, height: 35 },
    bodyOffset: { x: 120, y: 160 },
    portrait: 'gameAssets/blackLancerAvatar.png',
    theme: 'black',
    flipX: true,
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
  'black-lancer-guard-bot-16b': {
    name: 'Mysterious Stranger',
    text: '...',
    spriteKey: 'black-lancer-defense',
    frame: 4,
    scale: 0.75,
    bodySize: { width: 60, height: 35 },
    bodyOffset: { x: 120, y: 160 },
    portrait: 'gameAssets/blackLancerAvatar.png',
    theme: 'black',
    flipX: true,
    animated: true,
    repeatDelay: 200,
    delay: 200,
  },
};

